eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: reservation-service
  mongodb:
    uri: mongodb://localhost:27017/reservation_db

server:
  port: 8081